services:

  mongo_db:
    image: mongo
    restart: always
    container_name: mongo-docker-prepractice
    environment:
      MONGO_INITDB_ROOT_USERNAME: sabig
      MONGO_INITDB_ROOT_PASSWORD: Sabig0850
    ports:
      - "27017:27017"

  fast_api:
    build: ./fast_api
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./fast_api/:/app/
    depends_on:
      - mongo_db
    ports:
      - "8000:8000"
    restart: "no"