version: '3.3'

services:

  neo4j:
    image: neo4j:5.13.0
    restart: always
    environment:
      NEO4J_AUTH: neo4j/cn230_admin
    volumes:
      - ./neo_data:/data
    ports:
      - "7474:7474"
      - "7687:7687"

  fast_api:
    build: ./fast_api
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./fast_api/:/app/
    depends_on:
      - neo4j
    ports:
      - '8000:8000'
    restart: "no"
