version: '3.1'

services:
    db:
        image: mysql:8.1
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Qwerty4321
        ports:
            - "3306:3306"